### ISSUE TITLE
Cargo.lock should be committed

### ISSUE THREAD

**Issue by colemickens** [jokeyrhyme/nuls#16]
1. I can't package this for Nix easily.
2. It's appropriate/recommended to do so for binaries.

**Comment by jokeyrhyme** [comment]
Ah, will do

Good point!

**Comment by colemickens** [comment]
Thanks, I got an initial version building, need to test more:
* https://github.com/colemickens/nixpkgs/commit/5d94a8bae8636833faadbff5d8c53ea3eee12d47
* https://github.com/colemickens/nixcfg/commit/bbda65499819e171b0961f5df05b7d8d0e090986
